//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database_logic.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<double> precio_compra { get; set; }
        public Nullable<double> precio_venta { get; set; }
        public Nullable<double> ganancia { get; set; }
        public string descripcion { get; set; }
    }
}
