//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database_logic.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_productos
    {
        public int id { get; set; }
        public string Producto { get; set; }
        public string Categoria { get; set; }
        public Nullable<double> Precio_de_compra { get; set; }
        public Nullable<double> Precio_de_venta { get; set; }
        public Nullable<double> Ganancia { get; set; }
        public string Descripcion { get; set; }
    }
}
